pip install Rungui
pip install requests
pip install winshell
pip install psutil
pip install pypiwin32
pip install pycryptodome
pip install cryptography
pip install pillow
pip install discord_webhook
pip install rotate-screen
pip install pyperclip
pip install pygame
pip install pyinstaller
pip install undetected_chromedriver 
